name: Build Blink UF2

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write   # 🔥 bắt buộc để tạo release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi cmake build-essential python3
        sudo apt install -y libnewlib-arm-none-eabi
        sudo apt install -y binutils-arm-none-eabi
    
    - name: Clone FatFS
      run: |
        git clone https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico.git

    - name: Set PICO_SDK_PATH
      run: echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

    - name: Debug SDK path
      run: |
        echo $PICO_SDK_PATH
        ls $PICO_SDK_PATH
        ls -R .

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DPICO_SDK_PATH=$PICO_SDK_PATH
        make -j$(nproc)
        ls -R build

    - name: Upload UF2
      uses: actions/upload-artifact@v4
      with:
        name: blink-uf2
        path: build/*.uf2
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }}
        name: Auto Build ${{ github.run_number }}
        files: build/*.uf2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}